### ISSUE TITLE
erros when try to add water

### ISSUE THREAD

**Issue by MiguelDevelopper** [spimort/TerraBrush#153]
i got this bunch of errors when y try to add water flow or river id tried it in godot 4.3 and 4.4 

  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at TerraBrush.WaterFlowTool.<>c__DisplayClass4_0.<Paint>b__0(ImageZoneInfo imageZoneInfo, Single pixelBrushStrength) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 22
     at TerraBrush.ToolBase.ForEachBrushPixel(Image brushImage, Int32 brushSize, Vector2 imagePosition, OnBrushPixel onBrushPixel, Boolean ignoreLockedZone) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\ToolBase.cs:line 110
     at TerraBrush.WaterFlowTool.Paint(TerrainToolType toolType, Image brushImage, Int32 brushSize, Single brushStrength, Vector2 imagePosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 21
     at TerraBrush.TerraBrushTool.EditTerrain(Vector3 meshPosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\TerraBrushTool.cs:line 126
     at TerraBrush.Plugin._PhysicsProcess(Double delta) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Plugin.cs:line 243
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2471
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1497
     at TerraBrush.Plugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\angar\OneDrive\Documentos\left-behind\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\TerraBrush.Plugin_ScriptMethods.generated.cs:line 280
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at TerraBrush.WaterFlowTool.<>c__DisplayClass4_0.<Paint>b__0(ImageZoneInfo imageZoneInfo, Single pixelBrushStrength) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 22
     at TerraBrush.ToolBase.ForEachBrushPixel(Image brushImage, Int32 brushSize, Vector2 imagePosition, OnBrushPixel onBrushPixel, Boolean ignoreLockedZone) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\ToolBase.cs:line 110
     at TerraBrush.WaterFlowTool.Paint(TerrainToolType toolType, Image brushImage, Int32 brushSize, Single brushStrength, Vector2 imagePosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 21
     at TerraBrush.TerraBrushTool.EditTerrain(Vector3 meshPosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\TerraBrushTool.cs:line 126
     at TerraBrush.Plugin._PhysicsProcess(Double delta) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Plugin.cs:line 243
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2471
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1497
     at TerraBrush.Plugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\angar\OneDrive\Documentos\left-behind\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\TerraBrush.Plugin_ScriptMethods.generated.cs:line 280
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at TerraBrush.WaterFlowTool.<>c__DisplayClass4_0.<Paint>b__0(ImageZoneInfo imageZoneInfo, Single pixelBrushStrength) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 22
     at TerraBrush.ToolBase.ForEachBrushPixel(Image brushImage, Int32 brushSize, Vector2 imagePosition, OnBrushPixel onBrushPixel, Boolean ignoreLockedZone) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\ToolBase.cs:line 110
     at TerraBrush.WaterFlowTool.Paint(TerrainToolType toolType, Image brushImage, Int32 brushSize, Single brushStrength, Vector2 imagePosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Scripts\Tools\WaterFlowTool.cs:line 21
     at TerraBrush.TerraBrushTool.EditTerrain(Vector3 meshPosition) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\TerraBrushTool.cs:line 126
     at TerraBrush.Plugin._PhysicsProcess(Double delta) in C:\Users\angar\OneDrive\Documentos\left-behind\addons\terrabrush\Plugin.cs:line 243
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2471
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1497
     at TerraBrush.Plugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\angar\OneDrive\Documentos\left-behind\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\TerraBrush.Plugin_ScriptMethods.generated.cs:line 280
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24

**Comment by MiguelDevelopper** [comment]
forget to say also happens with snow

**Comment by MiguelDevelopper** [comment]
i restarted the engine and now it works, very strange

**Comment by spimort** [comment]
Make sure you add the water/snow definition AND you update the terrain before painting. Anyways, glad it works !
